name: ZotexCommons
version: 1.0.0
author: [TyTheOwl, ItsAlfiee]
main: net.zotex.zotexcommons.ZotexCommons
commands:
  help:
    description: Simple help command
    aliases: []
  nightvision:
    description: Nightvision command!
    aliases: [nv]